### PR TITLE
Rename to spandsp3

### PR DESCRIPTION
**Pull request by micmac1**
Hi all,

This is related to issue #5. It's just an idea at this point. Please let me know if this would be acceptable in general, then I'd put some more time into it and test it on device. Compiling works fine already and the installed output looks fine on first glance.

The main aim is that the new spandsp can coexist with the old. Kind of like libpcre and libpcre2 do it.

This renames the library to libspandsp3. The main header is also renamed
to spandsp3.h. The folder of the secondary headers is renamed to
spandsp3 likewise. This way libs and headers can co-exist with the older
spandsp version.

Programs using spandsp need to be adapted slightly to use the new
version, but this is acceptable as they need some code changes anyway.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

### CODE REVIEW

**Comment by mjerris** [comment]
there is a small handful of things that use spandsp.  and them updating to new version is trivial.  I don’t see the point in this change or the value in dev headers from both being installed at the same time.

**Comment by micmac1** [comment]
I think this would be the path of least resistance. This way us packagers do not run into trouble. Who  knows when upstreams update their sources. But up to you, of course.

Just as an example, in openwrt I put spandsp back into FS for the time being, because as is the new spandsp cannot be dropped into our staging area without causing issues with the other packages we ship.

**Comment by mjerris** [comment]
> I think this would be the path of least resistance. This way us packagers do not run into trouble. Who knows when upstreams update their sources. But up to you, of course. Just as an example, in openwrt I put spandsp back into FS for the time being, because as is the new spandsp cannot be dropped into our staging area without causing issues with the other packages we ship.

If a packager wants to take a different route it can be done so with only configure args.  You do not need to actually change the library name for this, it can be put into a subdir for headers and libs, and the pc file renamed to accomplish the same things.

**Comment by micmac1** [comment]
> > I think this would be the path of least resistance. This way us packagers do not run into trouble. Who knows when upstreams update their sources. But up to you, of course. Just as an example, in openwrt I put spandsp back into FS for the time being, because as is the new spandsp cannot be dropped into our staging area without causing issues with the other packages we ship.
> 
> If a packager wants to take a different route it can be done so with only configure args. You do not need to actually change the library name for this, it can be put into a subdir for headers and libs, and the pc file renamed to accomplish the same things.

Point taken, thanks! I'll close this pull request and also the related issue.

Kind regards,
Seb

**Pull request closed without merging**
